### PR TITLE
Various algorithms + fixes + clean ups!

### LINKED ISSUE #206: Avoid installing Clang 11 once it ships in Ubuntu 20.04 Workers in Azure Pipelines
Tracked by https://github.com/actions/virtual-environments/issues/2819

### LINKED ISSUE #246: LU decomposition for 3x3+ matrices are HORRIBLY off

### LINKED ISSUE #247: Proper support for solving system equations

### LINKED ISSUE #248: Determinant of 3x3+ matrices are off

### LINKED ISSUE #249: Fix completely inaccurate inverse
- [x] #247
- [x] #246 
- [x] #248

### LINKED ISSUE #252: Add public API for LU Decomposition

### LINKED ISSUE #253: Determinant in inverse can be different than actual determinant implementation

### LINKED ISSUE #254: CPOs should deduce allocator types to allow custom allocators

### LINKED ISSUE #257: [CI] Fail job if test fails to pass but still job results

### LINKED ISSUE #258: Add public API for forward/backward substitution

### LINKED ISSUE #259: Support common matrix aliases
- [x] `mpp::row_vector`
- [x] `mpp::column_vector`

- [x] `mpp::matrix2`
- [x] `mpp::matrix3`

- [x] `mpp::matrix2i`
- [x] `mpp::matrix2d`
- [x] `mpp::matrix2f`

- [x] `mpp::matrix3i`
- [x] `mpp::matrix3d`
- [x] `mpp::matrix3f`

### PR DESCRIPTION
**Pull request by sam20908**
Fixes #252 
Fixes #254 
Fixes #248 
Fixes #206 
Fixes #257 
Fixes #253 
Fixes #246 
Fixes #259 
Fixes #258 
Fixes #247 
Fixes #249 

### New public API changes
- `mpp::lu_decomposition`
- `mpp::forward_substitution`
- `mpp::back_substitution`
- Aliases (`mpp::row_vector`, `mpp::column_vector`, `mpp::matrix2i`, etc...)

### CODE REVIEW

**Review by sam20908 — COMMENTED** [review]
Need to check if `forward_substitution` and `back_substitution` requires any preconditions

File: include/mpp/algorithm/forward_substitution.hpp [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+			for (auto row = std::size_t{}; row < n; ++row)
+			{
+				auto result = static_cast<default_floating_type>(b[index_2d_to_1d(1, row, 0)]);
+
+				for (auto column = std::size_t{}; column < row; ++column)
+				{
+					result -= a[index_2d_to_1d(n, row, column)] * x_buffer[column];
+				}
+
+				result /= a[index_2d_to_1d(n, row, row)];
```
Comment (sam20908) [inline include/mpp/algorithm/forward_substitution.hpp:58]: Are there cases where this happens to divide by zero?

File: include/mpp/algorithm/inverse.hpp [hunk 2]
```diff
@@ -120,57 +125,70 @@ namespace mpp
...
+					auto part_inverse_buffer =
+						back_subst_on_buffer_unchecked<default_floating_type, RowsExtent, 1>(u_buffer,
+							std::move(l_x_buffer),
+							rows);
+
+					for (auto column = std::size_t{}; auto&& value : part_inverse_buffer)
+					{
+						inv_buffer[index_2d_to_1d(columns, column++, row)] = std::move(value);
+					}
+				}
```
Comment (sam20908) [inline include/mpp/algorithm/inverse.hpp:188]: **NOTE TO SELF**: This process of the for loop can be parallelized. Need to make an issue noting this.

File: include/mpp/algorithm/back_substitution.hpp [hunk 3]
```diff
@@ -0,0 +1,175 @@
...
+				const auto row_index = row - 1;
+
+				auto result = static_cast<default_floating_type>(b[index_2d_to_1d(1, row_index, 0)]);
+
+				for (auto column = n - 1; column > row_index; --column)
+				{
+					result -= a[index_2d_to_1d(n, row_index, column)] * x_buffer[column];
+				}
+
+				result /= a[index_2d_to_1d(n, row_index, row_index)];
```
Comment (sam20908) [inline include/mpp/algorithm/back_substitution.hpp:59]: Same thing with forward substitution: Could there be cases where we're dividing by 0 here?

File: include/mpp/algorithm/inverse.hpp (hunk 2 above)
Comment (sam20908) [reply include/mpp/algorithm/inverse.hpp]: Noted
